### ISSUE TITLE
최근 검색 기록 API 구현

### ISSUE THREAD

**Issue by vectorch9** [Instagram-Clone-Coding/React_instagram_clone#63]
## Feature Description

> description
### 기존의 검색 리팩토링
- 복잡하고 비효율적이었던 쿼리 일부를 개선했습니다. (데이터 수가 적어서 아마 체감은 안되실 것 같습니다.)
- `followingMemberFollow`가 특정 상황에 정상적으로 반환되지 않던 경우를 수정했습니다.
- 인스타그램의 경우 `followingMemberFollow`가 3명 이상인 경우 "aaa님, bbb님 외 *명이 팔로우 중입니다."식으로 출력이 되는데 현재 검색 API에선 `followingMemberFollow`에 해당하는 **모든** username을 반환합니다. 이 부분은 종강 후 수정할 예정입니다.

### 최근검색 관련 API
- 최근 검색 기록 삭제, 전체 삭제를 추가했습니다.
  - 전체삭제는 말그대로 로그인한 유저의 모든 검색기록을 삭제합니다.
  - 기록 삭제시 EntityType엔 `HASHTAG`, `MEMBER`를 넣어주시면 되고 EntityName엔 각각 해시태그 이름, 유저이름을 적어주시면 됩니다.
> "#만두"검색 기록을 삭제한다면 API요청시 `entityName`에 "만두"를 입력하면됩니다. "#만두"를 입력하는게 프론트에서 처리하기 더 편할까요 ? 이 부분은 의견 주시면 수정하겠습니다.
- 기존의 검색 조회수 증가 API가 확장됐습니다.
  - 검색 조회수 증가 + 최근검색기록 추가의 기능을 하게됩니다.
  - 기능이 두개가 됨에 따라 엔드포인트가 바뀌었습니다.
  - 즉, 기존의 조회수 증가 API 호출에서 엔드포인트만 바꿔주시면 됩니다.
## Todo
- [x] 최근 검색 API 적용

**Comment by vectorch9** [comment]
아 그리고 "조회수 증가+ 최근검색기록 추가" 호출시에도 삭제와 똑같이 입력해주시면 됩니다.

**Comment by okinawaa** [comment]
@bluetifulc 
너무 잘 구현해주셔서 감사합니다.
API 적용완료하였습니다! 만두 라고 보내는것보다 #만두 로 보내는것이 편할 것 같습니다.
#... 로 간다고 설계해주시면 감사하겠습니다!

**Comment by okinawaa** [comment]
PR merge 시에 issue 닫도록 하겠습니다 감사합니다.

**Comment by vectorch9** [comment]
> @bluetifulc 너무 잘 구현해주셔서 감사합니다. API 적용완료하였습니다! 만두 라고 보내는것보다 #만두 로 보내는것이 편할 것 같습니다. #... 로 간다고 설계해주시면 감사하겠습니다!

넵 그럼 이것도 `#만두` 형태로 바꾸겠습니다.

**Comment by okinawaa** [comment]
검색 기능 구현 완료하였습니다.
https://github.com/Instagram-Clone-Coding/React_instagram_clone/pull/76
