### ISSUE TITLE
백엔드 인증 관련 변경 사항

### ISSUE THREAD

**Issue by vectorch9** [Instagram-Clone-Coding/React_instagram_clone#71]
## Feature Description
- 백엔드 인증 관련 전반적인 로직이 수정되었습니다.
- 로그인, 코드를 통한 로그인, 재발급(Reissue) API가 리팩토링되었으니 프론트에서 정상 호출되는지 확인해주시면 감사하겠습니다.
- 일부 변경사항
  - 코드를 통한 로그인의 엔드포인트가 `/accounts/login/recovery`에서 `/login/recovery`로 수정되었습니다
  - 재발급 시도 시 기존의 "다른 기기에 의해 로그아웃 되었습니다"가 200 응답이 아닌 에러응답으로 변경되며 응답코드가 변경되었습니다.
- 최대한 기존과 응답, 호출은 변하지 않도록 리팩토링하였는데 혹시 바뀐 부분이 있으면 카톡으로 질문주시면 됩니다 !

**Comment by live-small** [comment]
## 수정 
- [x] 코드를 통한 로그인 엔드포인트 

## check list 
- [x] 로그인 
- [x] 코드를 통한 로그인 
- [x] 재발급

**Comment by live-small** [comment]
### 엔드포인트 수정 완료 - https://github.com/Instagram-Clone-Coding/React_instagram_clone/commit/920109f13ad66f2e3094cc2bd1b94bef33b0f3ae

로그인, 재발급 테스트 완료했습니다. 이슈 닫겠습니다.

**Comment by live-small** [comment]
@bluetifulc 
### 토큰 재발급 api에서 refresh token이 없을 때, 500대 에러가 뜨는게 맞나요? 
로그인 후에 다시 재방문했을 때, 로그인 후의 페이지를 보여주기 위해 
최상단에서 토큰 재발급 api를 호출하게 되는데, 
(유효한 refresh token이 있으면 토큰재발급으로 로그인처리하게 되고, 그렇지 않은 경우엔 로그인 페이지로 가게 됩니다) 
refresh token이 없을 때 500번대 에러가 뜨네요. 

## 에러메시지 
<img width="493" alt="스크린샷 2022-07-07 오후 3 08 13" src="https://user-images.githubusercontent.com/70274947/177703528-3e614a6d-b0da-4377-92ba-cb11f25f86d3.png">

```json
{
   "status":400,"code":"G006",
   "message":"request header가 유효하지 않습니다.",
   "errors":[{"field":"http method","value":"GET","reason":"허용되지 않은 HTTP method입니다."}]
}
```
## request 
<img width="495" alt="스크린샷 2022-07-07 오후 3 11 32" src="https://user-images.githubusercontent.com/70274947/177704048-00c5174b-d1ac-4d0e-9f20-89fa60a055bf.png">

**Comment by vectorch9** [comment]
쿠키(배열)에 refreshToken이 있는 지 검사하는 로직이 있는데, 쿠키 자체가 아예 비어있는 경우는 `NullPointerException`이 발생하고 있었습니다. 다음 배포 때 수정하겠습니다.
