### ISSUE TITLE
DM hotfix

### ISSUE THREAD

**Issue by seonpilKim** [Instagram-Clone-Coding/React_instagram_clone#77]
### 1. DM 페이지 접속 후 새로고침하면 발생하는 문제 
@seonpilKim @bluetifulc @ChanhyukPark-Tech @live-small 

처음에 DM 페이지로 접속하면 `/sub/dlwlrma`으로 구독이 잘 됩니다.
따라서 메시지를 전송하면 웹소켓을 통해 바로 메시지를 받을 수 있습니다.

https://user-images.githubusercontent.com/68049320/178110232-e83ec052-226f-4d09-a385-6a465e0cf515.mp4

https://user-images.githubusercontent.com/68049320/178110300-96693f84-a2a4-4067-9337-3111442213fc.mp4

https://user-images.githubusercontent.com/68049320/178110436-a376f4fd-3ba9-4c6a-8dab-0c4e7d33a303.mp4

그러나 DM 페이지에서 새로고침을 누르면 `/sub/undefined`으로 잘못 구독이 되어, 메시지를 전송해도 웹소켓을 통해 메시지를 받을 수 없게 되는 현상을 발견했습니다.

https://user-images.githubusercontent.com/68049320/178110360-b2d2fcae-aa61-47c2-ada7-00c9691b7d30.mp4

https://user-images.githubusercontent.com/68049320/178110403-df86ec19-4e62-400e-a8ae-9d6f54d47435.mp4

https://user-images.githubusercontent.com/68049320/178110423-4dab602a-6c35-4b3e-ac50-fc46ac25f824.mp4

___

### 2. 메시지 좋아요/취소를 누르면 서버로 요청 자체가 들어오지 않습니다.
@seonpilKim @bluetifulc @ChanhyukPark-Tech 

아래와 같이 웹소켓으로 메시지 전송을 하지 않습니다.

https://user-images.githubusercontent.com/68049320/178110653-dbdbd2d5-b185-448a-aebb-ee38b87ed411.mp4

또한, 서버에 어떠한 로그도 찍히지 않습니다. (서버에서 정상적으로 요청을 받으면, HTTP, DB 등의 로그가 남습니다.)

https://user-images.githubusercontent.com/68049320/178110723-f65349a8-5ec4-4da4-af60-f3c2b98b2ffe.mp4

p.s) 서버에서 정상적으로 요청을 받은 경우 아래와 같이 로그가 찍히게 됩니다.

https://user-images.githubusercontent.com/68049320/178110754-786caa80-90eb-46b5-95ab-5af3dc900410.mp4

참고로 웹소켓 통신은 헤더가 없어서 인증처리가 따로 없습니다.
프론트단에서도 코드 수정이 없다고 하셨지만, 서버도 마찬가지로 비즈니스 로직 수정을 한 게 없어서 어느 부분이 문제인지 파악하기가 어렵네요.. 일단 다같이 원인을 찾아봐야 할 것 같습니다.

## Todo
- [x] DM 페이지 새로고침 시 구독이 제대로 되지 않는 문제 해결
- [x] 메시지 좋아요/취소가 제대로 동작하지 않는 문제 해결

**Comment by vectorch9** [comment]
@ChanhyukPark-Tech @seonpilKim 
**1번 문제**에 대한 좀 더 자세한 분석입니다.
## userInfo 정보 확인
우선 테스트를 위해서 다음과 같이 서버 상의 코드에 console.log를 추가했습니다.
![image](https://user-images.githubusercontent.com/58378676/178198319-1259e033-55f5-41e7-a97f-08590ab6468c.png)

1. 다른 화면에서 DM 페이지로 접속하는 경우 다음과 같이 정상 출력 됩니다.
![image](https://user-images.githubusercontent.com/58378676/178198511-3c6dd2c2-721e-4761-97c8-1599bf4e528b.png)

2. DM 페이지에서 새로고침을 하는 경우 다음과 같이 출력됩니다. `userInfo`가 불러와지지 않았음을 확인했습니다.
![image](https://user-images.githubusercontent.com/58378676/178198571-7a4b0bf3-ebb3-49e2-9088-9a6953f0bb48.png)

## 추측?
제가 추측하는 원인으로는, 2번의 경우 재발급 API와 websocket connection가 동시에 동작해서 발생하는 것 같습니다.
**1번의 경우** DM 페이지 접속이전 다른 페이지에서 정상적인 로그인 토큰과 정보를 지닌 상태로 websocket 요청을 하기때문에 정상동작하고 **2번의 경우**는 새로고침 후 재발급 API와 websocket 요청이 동시에 발생하지 않을까 생각했습니다.
> DM 화면 왼쪽 채팅방 목록등의 일반적인 Http API 호출은 await 키워드가 있기 때문에 재발급 처리 이후 동작합니다. 

제가 nodejs, React를 잠깐 맛만봐서 세부 로직을 잘 알지는 못하는데, `useAppSelector`를 통해 `userInfo`를 불러올때 내부적으로 비동기 처리하는 로직이 있을까요? 만약 없다면 혹시 위 부분이 문제가 아닐지 확인해주시면 감사하겠습니다 ! (직접 확인해보려 했는데 nodejs를 능숙히 다루진 못하겠네요...)
