### ISSUE TITLE
DM 목록 오류

### ISSUE THREAD

**Issue by seonpilKim** [Instagram-Clone-Coding/React_instagram_clone#83]
## Feature Description
DM 목록이 보이지 않는 오류입니다.

https://user-images.githubusercontent.com/68049320/181687458-16fd7f98-b366-4b7a-8161-9dd518fc9ccf.mp4

## Todo
- [ ] todo1

**Comment by live-small** [comment]
500번대 에러였고, 백엔드쪽 수정 후 테스트 서버에서 잘작동하는 것 확인함.
