### ISSUE TITLE
게시물 좋아요/저장 오류

### ISSUE THREAD

**Issue by seonpilKim** [Instagram-Clone-Coding/React_instagram_clone#84]
## Feature Description

게시물 좋아요나 저장을 누르면 아래와 같이 동작합니다.

https://user-images.githubusercontent.com/68049320/181687613-de0b8c51-3373-4de2-8c12-8cbf9c079352.mp4

## Todo
- [ ] todo1

**Comment by live-small** [comment]
500번대 에러 -> 백엔드쪽 수정 후, 잘 작동합니다.
