### ISSUE TITLE
프로필 정보 변경 이벤트 오류

### ISSUE THREAD

**Issue by seonpilKim** [Instagram-Clone-Coding/React_instagram_clone#85]
## Feature Description
프로필 정보 변경 버튼(제출)을 누르면 이벤트가 나타나지 않아 변경되었는지/변경실패인지 확인하기가 어렵습니다.

https://user-images.githubusercontent.com/68049320/181687709-01cc962c-da4b-4240-9c69-e0836a8043e7.mp4

## Todo
- [x] todo1

**Comment by live-small** [comment]
제 pc에서는 잘작동하는 거 같은데 @kimyoungyin 은 어떻게 보이시나요?
